# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpencodeFroge < Formula
  desc "Terminal-based AI assistant for software development"
  homepage "https://github.com/opencode-ai/opencode"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Millsondylan/opencode/releases/download/v0.1.1/forge-mac-x86_64.tar.gz"
      sha256 "745a9e51a91779b1b0fbfbb177bef204406f1fe4c84346596b08c7416ca82fe1"

      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Millsondylan/opencode/releases/download/v0.1.1/forge-mac-arm64.tar.gz"
      sha256 "1679be23b2d640af4af86fb70ab79e2b88f321ee7d727d59bcf83fd13479e237"

      def install
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Millsondylan/opencode/releases/download/v0.1.1/forge-linux-x86_64.tar.gz"
      sha256 "bd72095e63d5d7d2adba829822d62711a51f3f514d8b28396e0133775fbc28d0"
      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Millsondylan/opencode/releases/download/v0.1.1/forge-linux-arm64.tar.gz"
      sha256 "cb9b599fc1f0f8c4fae7b0b077fd8c3dedda429b1db9fb4038708744445e1035"
      def install
        bin.install "forge"
      end
    end
  end
end
